export const dummy = {
  status: "OK",
  copyright:
    "Copyright (c) 2023 The New York Times Company. All Rights Reserved.",
  section: "home",
  last_updated: "2023-04-19T19:57:06-04:00",
  num_results: 27,
  results: [
    {
      section: "us",
      subsection: "politics",
      title:
        "Supreme Court Delays Decision on Abortion Pill, Preserving Access for Now",
      abstract:
        "The drug will remain widely available as the justices extended their deadline to Friday on whether to uphold the F.D.A.’s approval of the pill.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/abortion-pill-supreme-court.html",
      uri: "nyt://article/87aa46c6-87c5-598d-af53-bdd4905b471b",
      byline: "By Abbie VanSickle",
      item_type: "Article",
      updated_date: "2023-04-19T18:54:49-04:00",
      created_date: "2023-04-19T05:00:24-04:00",
      published_date: "2023-04-19T05:00:24-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Decisions and Verdicts",
        "Abortion",
        "Abortion Drugs",
        "Mifeprex (RU-486)",
        "Suits and Litigation (Civil)",
        "Drugs (Pharmaceuticals)",
        "Supreme Courts (State)",
        "Appeals Courts (US)",
      ],
      org_facet: [],
      per_facet: ["Alito, Samuel A Jr", "Kacsmaryk, Matthew"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-scotus-abortion-sub-qhvc/19dc-scotus-abortion-sub-qhvc-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "A federal judge in Texas recently declared that the F.D.A.’s approval of an abortion pill, mifepristone, was invalid.",
          copyright: "Anna Moneymaker/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-scotus-abortion-sub-qhvc/19dc-scotus-abortion-sub-qhvc-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "A federal judge in Texas recently declared that the F.D.A.’s approval of an abortion pill, mifepristone, was invalid.",
          copyright: "Anna Moneymaker/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-scotus-abortion-sub-qhvc/19dc-scotus-abortion-sub-qhvc-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "A federal judge in Texas recently declared that the F.D.A.’s approval of an abortion pill, mifepristone, was invalid.",
          copyright: "Anna Moneymaker/Getty Images",
        },
      ],
      short_url: "https://nyti.ms/3GX0VMS",
    },
    {
      section: "business",
      subsection: "media",
      title:
        "What’s Next for Dominion After Its $787.5 Million Settlement With Fox News?",
      abstract:
        "The election technology company has several more defamation lawsuits pending against public figures and news outlets.",
      url: "https://www.nytimes.com/2023/04/19/business/media/dominion-fox-news-settlement.html",
      uri: "nyt://article/45907dce-74c8-52cc-81c7-e85b591ef050",
      byline: "By Tiffany Hsu",
      item_type: "Article",
      updated_date: "2023-04-19T16:11:49-04:00",
      created_date: "2023-04-19T09:46:10-04:00",
      published_date: "2023-04-19T09:46:10-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Television",
        "News and News Media",
        "Suits and Litigation (Civil)",
        "Elections",
        "Compensation for Damages (Law)",
        "Freedom of the Press",
        "Voter Fraud (Election Fraud)",
        "Presidential Election of 2020",
        "Rumors and Misinformation",
        "Decisions and Verdicts",
        "Conspiracy Theories",
        "Voting Machines",
      ],
      org_facet: [
        "Dominion Voting Systems Corp",
        "Fox News Channel",
        "Staple Street Capital",
      ],
      per_facet: [
        "Lindell, Mike",
        "Giuliani, Rudolph W",
        "Murdoch, Rupert",
        "Oliver, Maggie Toulouse",
        "Poulos, John",
        "Powell, Sidney (Attorney)",
      ],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dominion-cwfh/19dominion-cwfh-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1366,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Justin Nelson, left, a lawyer for Dominion Voting Systems, and John Poulos, its founder and chief executive, outside Delaware Superior Court in Wilmington on Tuesday.",
          copyright: "Pete Marovich for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dominion-cwfh/19dominion-cwfh-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Justin Nelson, left, a lawyer for Dominion Voting Systems, and John Poulos, its founder and chief executive, outside Delaware Superior Court in Wilmington on Tuesday.",
          copyright: "Pete Marovich for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dominion-cwfh/19dominion-cwfh-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Justin Nelson, left, a lawyer for Dominion Voting Systems, and John Poulos, its founder and chief executive, outside Delaware Superior Court in Wilmington on Tuesday.",
          copyright: "Pete Marovich for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3AgDfiI",
    },
    {
      section: "arts",
      subsection: "television",
      title: "Everybody Knows What Fox News Is Now",
      abstract:
        "Even without a trial, the Dominion suit made plain that the network’s main goal is the maintenance of a reality bubble.",
      url: "https://www.nytimes.com/2023/04/19/arts/television/fox-news-settlement.html",
      uri: "nyt://article/9d425f5f-8c1c-50c5-bdf6-f71748ecc1f6",
      byline: "By James Poniewozik",
      item_type: "Article",
      updated_date: "2023-04-19T10:54:28-04:00",
      created_date: "2023-04-19T10:39:21-04:00",
      published_date: "2023-04-19T10:39:21-04:00",
      material_type_facet: "",
      kicker: "Critic’s Notebook",
      des_facet: [
        "Television",
        "News and News Media",
        "Rumors and Misinformation",
      ],
      org_facet: ["Fox News Channel", "Dominion Voting Systems Corp"],
      per_facet: [
        "Carlson, Tucker",
        "Murdoch, Rupert",
        "Trump, Donald J",
        "Biden, Joseph R Jr",
      ],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19fox-notebook-pfml/19fox-notebook-pfml-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1366,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Fox News reached a settlement in the defamation suit brought by Dominion Voting Systems, agreeing to pay $787.5 million.",
          copyright: "Yuki Iwamura/Associated Press",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19fox-notebook-pfml/19fox-notebook-pfml-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Fox News reached a settlement in the defamation suit brought by Dominion Voting Systems, agreeing to pay $787.5 million.",
          copyright: "Yuki Iwamura/Associated Press",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19fox-notebook-pfml/19fox-notebook-pfml-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Fox News reached a settlement in the defamation suit brought by Dominion Voting Systems, agreeing to pay $787.5 million.",
          copyright: "Yuki Iwamura/Associated Press",
        },
      ],
      short_url: "https://nyti.ms/3ootEUG",
    },
    {
      section: "nyregion",
      subsection: "",
      title:
        "Victim’s Father Breaks Down as Bail Is Denied in Wrong-Driveway Shooting",
      abstract:
        "Kaylin Gillis’s death “touches a chord across the country,” the Washington County district attorney said during a court hearing in the case.",
      url: "https://www.nytimes.com/2023/04/19/nyregion/kaylin-gillis-father-wrong-driveway-shooting.html",
      uri: "nyt://article/62121b07-563f-5dc1-99de-d33e897a0547",
      byline: "By Jesse McKinley, Jay Root and Chelsia Rose Marcius",
      item_type: "Article",
      updated_date: "2023-04-19T19:19:48-04:00",
      created_date: "2023-04-19T15:34:38-04:00",
      published_date: "2023-04-19T15:34:38-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Murders, Attempted Murders and Homicides",
        "Decisions and Verdicts",
        "Deaths (Fatalities)",
        "Firearms",
      ],
      org_facet: [],
      per_facet: ["Gillis, Kaylin (2003-23)", "Monahan, Kevin D (1957- )"],
      geo_facet: ["Hebron (NY)", "Fort Edward (NY)"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-shooting-01-tvqc/19ny-shooting-01-tvqc-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1287,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew Gillis, the victim’s father, spoke for the first time to reporters since his daughter’s death.",
          copyright: "Benjamin Cleeton for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-shooting-01-tvqc/19ny-shooting-01-tvqc-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew Gillis, the victim’s father, spoke for the first time to reporters since his daughter’s death.",
          copyright: "Benjamin Cleeton for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-shooting-01-tvqc/19ny-shooting-01-tvqc-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew Gillis, the victim’s father, spoke for the first time to reporters since his daughter’s death.",
          copyright: "Benjamin Cleeton for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3URbO8F",
    },
    {
      section: "us",
      subsection: "",
      title: "Hundreds of Miles Apart, Separate Shootings Follow Wrong Turns",
      abstract:
        "Two men appeared in courtrooms in different parts of the country on Wednesday, charged in shootings that came after minor missteps on everyday tasks.",
      url: "https://www.nytimes.com/2023/04/19/us/yarl-gillis-shooting-missouri-ny.html",
      uri: "nyt://article/9826a8e7-aa93-5f04-b105-93c0b8177a78",
      byline: "By Julie Bosman, Mitch Smith, Jesse McKinley and Jay Root",
      item_type: "Article",
      updated_date: "2023-04-19T19:43:00-04:00",
      created_date: "2023-04-19T16:56:58-04:00",
      published_date: "2023-04-19T16:56:58-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Assaults"],
      org_facet: [],
      per_facet: ["Yarl, Ralph"],
      geo_facet: ["Kansas City (Mo)"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19nat-suspects-top-kfjw/19nat-suspects-top-kfjw-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1152,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew D. Lester, charged in the shooting of Ralph Yarl, pleaded not guilty on Wednesday.",
          copyright: "KCNA, via Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19nat-suspects-top-kfjw/19nat-suspects-top-kfjw-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew D. Lester, charged in the shooting of Ralph Yarl, pleaded not guilty on Wednesday.",
          copyright: "KCNA, via Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19nat-suspects-top-kfjw/19nat-suspects-top-kfjw-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Andrew D. Lester, charged in the shooting of Ralph Yarl, pleaded not guilty on Wednesday.",
          copyright: "KCNA, via Reuters",
        },
      ],
      short_url: "https://nyti.ms/43L41xr",
    },
    {
      section: "us",
      subsection: "",
      title: "What Are ‘Stand Your Ground’ Laws, and When Do They Apply?",
      abstract:
        "The shootings of two people who mistakenly approached homes in Missouri and New York have renewed attention to self-defense laws across the country.",
      url: "https://www.nytimes.com/2023/04/19/us/stand-your-ground-laws-states.html",
      uri: "nyt://article/c3184500-010d-5e06-b621-e23c06d413f3",
      byline: "By Adeel Hassan",
      item_type: "Article",
      updated_date: "2023-04-19T13:31:57-04:00",
      created_date: "2023-04-19T13:29:29-04:00",
      published_date: "2023-04-19T13:29:29-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Law and Legislation",
        "Self-Defense",
        "Murders, Attempted Murders and Homicides",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19NAT-STAND-YOUR-GROUND-01-jzvt/19NAT-STAND-YOUR-GROUND-01-jzvt-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "People in Kansas City, Mo., rallied for Ralph Yarl, who was shot last Thursday when he went to the wrong house looking to pick up his younger brothers.",
          copyright: "Arin Yoon for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19NAT-STAND-YOUR-GROUND-01-jzvt/19NAT-STAND-YOUR-GROUND-01-jzvt-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "People in Kansas City, Mo., rallied for Ralph Yarl, who was shot last Thursday when he went to the wrong house looking to pick up his younger brothers.",
          copyright: "Arin Yoon for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19NAT-STAND-YOUR-GROUND-01-jzvt/19NAT-STAND-YOUR-GROUND-01-jzvt-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "People in Kansas City, Mo., rallied for Ralph Yarl, who was shot last Thursday when he went to the wrong house looking to pick up his younger brothers.",
          copyright: "Arin Yoon for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3UMdJeU",
    },
    {
      section: "world",
      subsection: "europe",
      title:
        "‘Our Own Guys Are Shelling Us’: How Russian Propaganda Plagues Ukraine",
      abstract:
        "A year into the war, some residents of eastern Ukrainian towns still confound officials and the police with their support for Russia despite the constant bombardment from Russian forces.",
      url: "https://www.nytimes.com/2023/04/19/world/europe/ukraine-russia-donbas-propaganda.html",
      uri: "nyt://article/3ecf6bd4-99e5-5771-b4ac-486f789b2b2c",
      byline:
        "By Carlotta Gall, Oleksandr Chubko, Dyma Shapoval and Daniel Berehulak",
      item_type: "Article",
      updated_date: "2023-04-19T15:23:04-04:00",
      created_date: "2023-04-19T13:38:33-04:00",
      published_date: "2023-04-19T13:38:33-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Russian Invasion of Ukraine (2022)",
        "Propaganda",
        "Defense and Military Forces",
        "Rumors and Misinformation",
        "Social Media",
        "Evacuations and Evacuees",
      ],
      org_facet: [],
      per_facet: ["Zelensky, Volodymyr"],
      geo_facet: ["Donbas (Ukraine)", "Russia"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ukraine-propaganda-promo/19ukraine-propaganda-01-vzmf-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Natasha, right, standing with a neighbor outside of her home, the site of a Russian strike, last month in Kostyantynivka, Ukraine.",
          copyright: "Daniel Berehulak/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ukraine-propaganda-promo/19ukraine-propaganda-01-vzmf-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Natasha, right, standing with a neighbor outside of her home, the site of a Russian strike, last month in Kostyantynivka, Ukraine.",
          copyright: "Daniel Berehulak/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ukraine-propaganda-promo/19ukraine-propaganda-01-vzmf-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Natasha, right, standing with a neighbor outside of her home, the site of a Russian strike, last month in Kostyantynivka, Ukraine.",
          copyright: "Daniel Berehulak/The New York Times",
        },
      ],
      short_url: "https://nyti.ms/43Mqeel",
    },
    {
      section: "style",
      subsection: "",
      title: "What Would You Do for a Taylor Swift Sweatshirt?",
      abstract:
        "Outside a stadium in Tampa, hundreds of fans waited overnight in the rain before scrambling for Eras Tour merch.",
      url: "https://www.nytimes.com/2023/04/19/style/taylor-swift-mania.html",
      uri: "nyt://article/ac6e3d11-9e96-5138-88dd-97a35537f574",
      byline: "By Madison Malone Kircher",
      item_type: "Article",
      updated_date: "2023-04-19T16:29:38-04:00",
      created_date: "2023-04-19T10:45:23-04:00",
      published_date: "2023-04-19T10:45:23-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Pop and Rock Music",
        "internal-sub-only",
        "Women and Girls",
        "Social Media",
        "Fans (Persons)",
        "Memorabilia and Souvenirs",
        "T-Shirts (Apparel)",
      ],
      org_facet: [],
      per_facet: ["Swift, Taylor"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/18/multimedia/00TAYLOR-SWIFT-PARKING-LOT-01-kchf/00TAYLOR-SWIFT-PARKING-LOT-01-kchf-superJumbo.jpg",
          format: "Super Jumbo",
          height: 2048,
          width: 1639,
          type: "image",
          subtype: "photo",
          caption:
            "Annabella Siegel carries away her haul of tour souvenirs in Tampa.",
          copyright: "Zack Wittman for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/18/multimedia/00TAYLOR-SWIFT-PARKING-LOT-01-kchf/00TAYLOR-SWIFT-PARKING-LOT-01-kchf-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Annabella Siegel carries away her haul of tour souvenirs in Tampa.",
          copyright: "Zack Wittman for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/18/multimedia/00TAYLOR-SWIFT-PARKING-LOT-01-kchf/00TAYLOR-SWIFT-PARKING-LOT-01-kchf-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Annabella Siegel carries away her haul of tour souvenirs in Tampa.",
          copyright: "Zack Wittman for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/43NMwfO",
    },
    {
      section: "us",
      subsection: "politics",
      title: "Republicans Hit DeSantis Over Disney Feud",
      abstract:
        "As Gov. Ron DeSantis of Florida escalates a fight against his state’s largest private employer, his potential rivals for the White House see an opening to attack.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/desantis-disney-gop.html",
      uri: "nyt://article/3a6d1fb6-0bb0-5c55-9596-7b44a8ab5885",
      byline: "By Maggie Haberman",
      item_type: "Article",
      updated_date: "2023-04-19T16:30:40-04:00",
      created_date: "2023-04-19T12:56:58-04:00",
      published_date: "2023-04-19T12:56:58-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Presidential Election of 2024",
        "Primaries and Caucuses",
        "Conservatism (US Politics)",
        "United States Politics and Government",
      ],
      org_facet: ["Walt Disney Company", "Republican Party"],
      per_facet: ["DeSantis, Ron"],
      geo_facet: ["Florida"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-desantis-disney-bhzg/19pol-desantis-disney-bhzg-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1536,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis of Florida has continued to clash with Disney, the largest private employer in the state.",
          copyright: "Octavio Jones/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-desantis-disney-bhzg/19pol-desantis-disney-bhzg-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis of Florida has continued to clash with Disney, the largest private employer in the state.",
          copyright: "Octavio Jones/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-desantis-disney-bhzg/19pol-desantis-disney-bhzg-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis of Florida has continued to clash with Disney, the largest private employer in the state.",
          copyright: "Octavio Jones/Reuters",
        },
      ],
      short_url: "https://nyti.ms/3A8y58J",
    },
    {
      section: "business",
      subsection: "",
      title: "DeSantis Appointees Seek to ‘Void’ Disney World Agreement",
      abstract:
        "A board overseeing the resort wants lawyers to prepare a resolution to stop Disney from maintaining vast control over the complex for decades to come.",
      url: "https://www.nytimes.com/2023/04/19/business/ron-desantis-disney-world.html",
      uri: "nyt://article/2aa19b97-effb-5fdc-9d17-1c3de7b7fe51",
      byline: "By Brooks Barnes",
      item_type: "Article",
      updated_date: "2023-04-19T17:15:23-04:00",
      created_date: "2023-04-19T16:37:52-04:00",
      published_date: "2023-04-19T16:37:52-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Amusement and Theme Parks", "Governors (US)"],
      org_facet: [
        "Disney, Walt, World (Lake Buena Vista, Fla)",
        "Walt Disney Company",
      ],
      per_facet: ["DeSantis, Ron"],
      geo_facet: ["Orlando (Fla)", "Florida"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19Disney-sub-pwgj/19Disney-sub-pwgj-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1536,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis and the Walt Disney Company have been sparring for more than a year over a tax district that encompasses Disney World.",
          copyright: "Octavio Jones/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19Disney-sub-pwgj/19Disney-sub-pwgj-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis and the Walt Disney Company have been sparring for more than a year over a tax district that encompasses Disney World.",
          copyright: "Octavio Jones/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19Disney-sub-pwgj/19Disney-sub-pwgj-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Gov. Ron DeSantis and the Walt Disney Company have been sparring for more than a year over a tax district that encompasses Disney World.",
          copyright: "Octavio Jones/Reuters",
        },
      ],
      short_url: "https://nyti.ms/3Hl24yj",
    },
    {
      section: "world",
      subsection: "africa",
      title:
        "Uneven Cease-Fire in Sudan Makes Escape Hard for Desperate Civilians",
      abstract:
        "The army and the paramilitary group it is battling agreed to a 24-hour cease-fire. But many residents were unsure whether the truce was solid enough to safely flee.",
      url: "https://www.nytimes.com/2023/04/19/world/africa/sudan-fighting-ceasefire.html",
      uri: "nyt://article/5462adfc-7b9f-5d51-947e-afce2fa6e1f4",
      byline: "By Declan Walsh, Elian Peltier and Cora Engelbrecht",
      item_type: "Article",
      updated_date: "2023-04-19T19:26:55-04:00",
      created_date: "2023-04-19T19:02:46-04:00",
      published_date: "2023-04-19T19:02:46-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "War and Armed Conflicts",
        "Evacuations and Evacuees",
        "Defense and Military Forces",
      ],
      org_facet: ["Rapid Support Forces (Sudan)"],
      per_facet: ["al-Burhan, Abdel Fattah", "Hamdan, Mohamed (Hemeti)"],
      geo_facet: ["Sudan", "Khartoum (Sudan)"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19sudan-ledeall-1-kbfm/19sudan-ledeall-1-kbfm-superJumbo.jpg",
          format: "Super Jumbo",
          height: 960,
          width: 1280,
          type: "image",
          subtype: "photo",
          caption: "People trying to flee Khartoum, Sudan, on Wednesday.",
          copyright: "El Tayeb Siddig/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19sudan-ledeall-1-kbfm/19sudan-ledeall-1-kbfm-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "People trying to flee Khartoum, Sudan, on Wednesday.",
          copyright: "El Tayeb Siddig/Reuters",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19sudan-ledeall-1-kbfm/19sudan-ledeall-1-kbfm-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "People trying to flee Khartoum, Sudan, on Wednesday.",
          copyright: "El Tayeb Siddig/Reuters",
        },
      ],
      short_url: "https://nyti.ms/3mVScnk",
    },
    {
      section: "health",
      subsection: "",
      title: "U.S. Authorizes a New Round of Covid Boosters",
      abstract:
        "Older Americans and those with weakened immune systems, groups still particularly vulnerable to the virus, may receive additional shots of the reformulated vaccine, federal officials said.",
      url: "https://www.nytimes.com/2023/04/19/health/covid-boosters-seniors.html",
      uri: "nyt://article/31f7fd57-78b6-5f01-be45-31c563fcbafb",
      byline: "By Apoorva Mandavilli",
      item_type: "Article",
      updated_date: "2023-04-19T17:10:46-04:00",
      created_date: "2023-04-19T17:10:46-04:00",
      published_date: "2023-04-19T17:10:46-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "your-feed-science",
        "Coronavirus (2019-nCoV)",
        "Vaccination and Immunization",
        "Elderly",
        "Immune System",
        "Coronavirus Omicron Variant",
        "Viruses",
      ],
      org_facet: ["Centers for Disease Control and Prevention"],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19virus-boosters-vjpz/19virus-boosters-vjpz-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "The C.D.C. said only about 43 percent of adults 65 and older had received their first booster shot.",
          copyright: "Kenny Holston for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19virus-boosters-vjpz/19virus-boosters-vjpz-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "The C.D.C. said only about 43 percent of adults 65 and older had received their first booster shot.",
          copyright: "Kenny Holston for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19virus-boosters-vjpz/19virus-boosters-vjpz-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "The C.D.C. said only about 43 percent of adults 65 and older had received their first booster shot.",
          copyright: "Kenny Holston for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3AcIf8d",
    },
    {
      section: "nyregion",
      subsection: "",
      title:
        "Garage That Collapsed, Killing One, Was Due for Inspection This Year",
      abstract:
        "The parking structure in Lower Manhattan, originally built in 1925, had unresolved safety violations, city officials said.",
      url: "https://www.nytimes.com/2023/04/19/nyregion/nyc-garage-collapse.html",
      uri: "nyt://article/f1911c14-0aa5-5418-932b-c8c4184f4841",
      byline: "By Patrick McGeehan and Hurubie Meko",
      item_type: "Article",
      updated_date: "2023-04-19T19:18:45-04:00",
      created_date: "2023-04-19T18:58:51-04:00",
      published_date: "2023-04-19T18:58:51-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Accidents and Safety",
        "Parking",
        "Buildings (Structures)",
        "Parking Garages and Lots",
        "Surfside, Fla, Building Collapse (2021)",
        "Engineering and Engineers",
      ],
      org_facet: ["Buildings Department (NYC)"],
      per_facet: [],
      geo_facet: [
        "Financial District (Manhattan, NY)",
        "Manhattan (NYC)",
        "New York City",
      ],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-garage-bclg/19ny-garage-bclg-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Answers as to what caused the collapse of a parking garage in Lower Manhattan, killing one and injuring five others, were not immediately forthcoming.",
          copyright: "Earl Wilson/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-garage-bclg/19ny-garage-bclg-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Answers as to what caused the collapse of a parking garage in Lower Manhattan, killing one and injuring five others, were not immediately forthcoming.",
          copyright: "Earl Wilson/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19ny-garage-bclg/19ny-garage-bclg-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Answers as to what caused the collapse of a parking garage in Lower Manhattan, killing one and injuring five others, were not immediately forthcoming.",
          copyright: "Earl Wilson/The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3MXHhUR",
    },
    {
      section: "us",
      subsection: "politics",
      title:
        "House G.O.P. Unveils Debt Limit Bill Lifting Borrowing Cap for One Year",
      abstract:
        "The proposal would impose work requirements on food stamp and Medicaid recipients and repeal funding to beef up tax enforcement.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/house-republicans-debt-limit-bill.html",
      uri: "nyt://article/f67fc5e9-8d25-52f2-aa70-cc275ed664f0",
      byline: "By Catie Edmondson",
      item_type: "Article",
      updated_date: "2023-04-19T16:52:11-04:00",
      created_date: "2023-04-19T15:34:10-04:00",
      published_date: "2023-04-19T15:34:10-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "United States Politics and Government",
        "Federal Budget (US)",
      ],
      org_facet: ["House of Representatives", "Republican Party"],
      per_facet: ["McCarthy, Kevin (1965- )"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-debtlimit-1-kjgw/19dc-debtlimit-1-kjgw-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1366,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Speaker Kevin McCarthy said he would put legislation to a vote in the House next week regarding the debt ceiling.",
          copyright: "Jeenah Moon for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-debtlimit-1-kjgw/19dc-debtlimit-1-kjgw-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Speaker Kevin McCarthy said he would put legislation to a vote in the House next week regarding the debt ceiling.",
          copyright: "Jeenah Moon for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-debtlimit-1-kjgw/19dc-debtlimit-1-kjgw-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Speaker Kevin McCarthy said he would put legislation to a vote in the House next week regarding the debt ceiling.",
          copyright: "Jeenah Moon for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3UXdEVJ",
    },
    {
      section: "arts",
      subsection: "music",
      title:
        "An A.I. Hit of Fake ‘Drake’ and ‘The Weeknd’ Rattles the Music World",
      abstract:
        "A track like “Heart on My Sleeve,” which went viral before being taken down by streaming services this week, may be a novelty for now. But the legal and creative questions it raises are here to stay.",
      url: "https://www.nytimes.com/2023/04/19/arts/music/ai-drake-the-weeknd-fake.html",
      uri: "nyt://article/78969b4b-b866-5a27-ae64-8527cde6e345",
      byline: "By Joe Coscarelli",
      item_type: "Article",
      updated_date: "2023-04-19T17:02:25-04:00",
      created_date: "2023-04-19T16:40:22-04:00",
      published_date: "2023-04-19T16:40:22-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Music",
        "Rap and Hip-Hop",
        "Pop and Rock Music",
        "Artificial Intelligence",
        "Copyrights and Copyright Violations",
        "Intellectual Property",
        "Audio Recordings, Downloads and Streaming",
        "Computers and the Internet",
      ],
      org_facet: ["Universal Music Group"],
      per_facet: [
        "Drake (Rapper)",
        "Tesfaye, Abel (Weeknd)",
        "Herndon, Holly (1980- )",
      ],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19AI-SONGS-02-cjlw/19AI-SONGS-02-cjlw-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Labels hope that fans will continue to prize the work of artists, including the real Drake, above that of A.I.-generated imitations. ",
          copyright: "Adam Riding for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19AI-SONGS-02-cjlw/19AI-SONGS-02-cjlw-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Labels hope that fans will continue to prize the work of artists, including the real Drake, above that of A.I.-generated imitations. ",
          copyright: "Adam Riding for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19AI-SONGS-02-cjlw/19AI-SONGS-02-cjlw-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Labels hope that fans will continue to prize the work of artists, including the real Drake, above that of A.I.-generated imitations. ",
          copyright: "Adam Riding for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/40m1eaT",
    },
    {
      section: "sports",
      subsection: "",
      title:
        "A 50-Mile Race, a Quick Car Ride and a Scandal at the Finish Line",
      abstract:
        "An ultramarathoner was disqualified after covering part of a course in a friend’s car. She said it was a “miscommunication.” A rival had a different word: cheating.",
      url: "https://www.nytimes.com/2023/04/19/sports/joasia-zakrzewski-ultramarathon-cheating.html",
      uri: "nyt://article/9fd69503-6809-5926-9e8f-ba282436cfeb",
      byline: "By Victor Mather",
      item_type: "Article",
      updated_date: "2023-04-19T14:36:51-04:00",
      created_date: "2023-04-19T13:49:12-04:00",
      published_date: "2023-04-19T13:49:12-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Ultramarathon Running", "Cheating"],
      org_facet: [],
      per_facet: ["Zakrzewski, Joasia"],
      geo_facet: ["England"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/sports/19runner/19runner-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1367,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Joasia Zakrzewski competing in an ultramarathon in Norway in 2016.",
          copyright: "Kai-Otto Melau/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/sports/19runner/19runner-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Joasia Zakrzewski competing in an ultramarathon in Norway in 2016.",
          copyright: "Kai-Otto Melau/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/sports/19runner/19runner-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Joasia Zakrzewski competing in an ultramarathon in Norway in 2016.",
          copyright: "Kai-Otto Melau/Getty Images",
        },
      ],
      short_url: "https://nyti.ms/41xBpWy",
    },
    {
      section: "opinion",
      subsection: "editorials",
      title: "Fox News Remains an Aberration in American Journalism",
      abstract:
        "A trial would have demonstrated the full extent of the company’s practice of deliberate deceit.",
      url: "https://www.nytimes.com/2023/04/19/opinion/editorials/fox-news-settlement.html",
      uri: "nyt://article/cf21a3cc-0983-5aa5-add7-253c0509232f",
      byline: "By David Firestone",
      item_type: "Article",
      updated_date: "2023-04-19T19:38:02-04:00",
      created_date: "2023-04-19T13:32:56-04:00",
      published_date: "2023-04-19T13:32:56-04:00",
      material_type_facet: "",
      kicker: "David Firestone",
      des_facet: [
        "News and News Media",
        "Libel and Slander",
        "Freedom of the Press",
        "Suits and Litigation (Civil)",
        "Decisions and Verdicts",
        "Ethics and Official Misconduct",
        "Presidential Election of 2020",
      ],
      org_facet: [
        "Dominion Voting Systems Corp",
        "Fox News Channel",
        "Smartmatic SGO Group",
      ],
      per_facet: ["Murdoch, Rupert"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19firestoneSub-qmbj/19firestoneSub-qmbj-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Drew Angerer/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19firestoneSub-qmbj/19firestoneSub-qmbj-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Drew Angerer/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19firestoneSub-qmbj/19firestoneSub-qmbj-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Drew Angerer/Getty Images",
        },
      ],
      short_url: "https://nyti.ms/3A95OPk",
    },
    {
      section: "opinion",
      subsection: "",
      title: "How Fox Helped Break the American Right",
      abstract:
        "The roots of the network’s reckoning can be found in the John Birch Society and an alternate political tradition.",
      url: "https://www.nytimes.com/2023/04/19/opinion/fox-dominion-john-birch-society.html",
      uri: "nyt://article/2f9b010b-b7e1-54bb-9391-c21de9ba742c",
      byline: "By Matthew Dallek",
      item_type: "Article",
      updated_date: "2023-04-19T18:11:16-04:00",
      created_date: "2023-04-19T09:19:18-04:00",
      published_date: "2023-04-19T09:19:18-04:00",
      material_type_facet: "",
      kicker: "Guest Essay",
      des_facet: [
        "Rumors and Misinformation",
        "Conspiracy Theories",
        "Right-Wing Extremism and Alt-Right",
        "Suits and Litigation (Civil)",
        "United States Politics and Government",
        "Conservatism (US Politics)",
      ],
      org_facet: ["Fox News Channel", "John Birch Society", "Republican Party"],
      per_facet: [
        "Carlson, Tucker",
        "Hannity, Sean",
        "Ingraham, Laura A",
        "Murdoch, Rupert",
      ],
      geo_facet: ["United States"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/19dallek-1/19dallek-1-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1485,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "A 1962 sign from the John Birch Society imploring people to impeach Chief Justice Earl Warren.",
          copyright: "Duane Howell/The Denver Post, via Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/19dallek-1/19dallek-1-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "A 1962 sign from the John Birch Society imploring people to impeach Chief Justice Earl Warren.",
          copyright: "Duane Howell/The Denver Post, via Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/19dallek-1/19dallek-1-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "A 1962 sign from the John Birch Society imploring people to impeach Chief Justice Earl Warren.",
          copyright: "Duane Howell/The Denver Post, via Getty Images",
        },
      ],
      short_url: "https://nyti.ms/41CD7G6",
    },
    {
      section: "opinion",
      subsection: "",
      title: "Why Fox Had to Settle",
      abstract: "A defeat for both the network and the public.",
      url: "https://www.nytimes.com/2023/04/18/opinion/fox-news-dominion-settlement.html",
      uri: "nyt://article/81ee581a-c690-51b8-b38f-a1cbc15a5608",
      byline: "By Michelle Goldberg",
      item_type: "Article",
      updated_date: "2023-04-19T12:28:20-04:00",
      created_date: "2023-04-18T20:50:46-04:00",
      published_date: "2023-04-18T20:50:46-04:00",
      material_type_facet: "",
      kicker: "Michelle Goldberg",
      des_facet: [
        "Television",
        "News and News Media",
        "Libel and Slander",
        "Suits and Litigation (Civil)",
        "Voter Fraud (Election Fraud)",
      ],
      org_facet: [
        "Dominion Voting Systems Corp",
        "Fox News Channel",
        "Smartmatic SGO Group",
        "Fox Corporation",
      ],
      per_facet: [],
      geo_facet: ["Delaware"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/18goldberg2/18goldberg2-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "In-camera multiple exposure by Mark Peterson/Redux",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/18goldberg2/18goldberg2-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "In-camera multiple exposure by Mark Peterson/Redux",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/20/opinion/18goldberg2/18goldberg2-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "In-camera multiple exposure by Mark Peterson/Redux",
        },
      ],
      short_url: "https://nyti.ms/3mSkcZ3",
    },
    {
      section: "opinion",
      subsection: "",
      title: "I Want to Be the Old Man With the Orange Socks",
      abstract:
        "I’ve often been delighted by how older men lean into sartorial whimsy when they exit workplace life.",
      url: "https://www.nytimes.com/2023/04/19/opinion/orange-socks-older-age.html",
      uri: "nyt://article/137d0510-f9c2-5f26-b595-a994b3da2b97",
      byline: "By Charles M. Blow",
      item_type: "Article",
      updated_date: "2023-04-19T19:00:07-04:00",
      created_date: "2023-04-19T19:00:07-04:00",
      published_date: "2023-04-19T19:00:07-04:00",
      material_type_facet: "",
      kicker: "Charles M. Blow",
      des_facet: [
        "Fashion and Apparel",
        "Art",
        "Men and Boys",
        "Freedom of Speech and Expression",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/opinion/19blow1/19blow1-superJumbo.jpg",
          format: "Super Jumbo",
          height: 2048,
          width: 1621,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/opinion/19blow1/19blow1-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/opinion/19blow1/19blow1-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Getty Images",
        },
      ],
      short_url: "https://nyti.ms/3LceoD4",
    },
    {
      section: "briefing",
      subsection: "",
      title: "Your Wednesday Evening Briefing",
      abstract: "Here’s what you need to know at the end of the day.",
      url: "https://www.nytimes.com/2023/04/19/briefing/supreme-court-abortion-pill-india-china-population.html",
      uri: "nyt://article/ac1283c3-f1b5-5a0c-87ac-7f23b74c4452",
      byline: "By Matthew Cullen",
      item_type: "Article",
      updated_date: "2023-04-19T17:45:27-04:00",
      created_date: "2023-04-19T17:45:27-04:00",
      published_date: "2023-04-19T17:45:27-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19evening-briefing-nl-ABORTION-01-jpwk/19evening-briefing-nl-ABORTION-01-jpwk-superJumbo.jpg",
          format: "Super Jumbo",
          height: 2047,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "Conflicting federal court decisions led the Supreme Court to rule on the restriction of abortion pills.",
          copyright: "Anna Moneymaker/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19evening-briefing-nl-ABORTION-01-jpwk/19evening-briefing-nl-ABORTION-01-jpwk-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "Conflicting federal court decisions led the Supreme Court to rule on the restriction of abortion pills.",
          copyright: "Anna Moneymaker/Getty Images",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19evening-briefing-nl-ABORTION-01-jpwk/19evening-briefing-nl-ABORTION-01-jpwk-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "Conflicting federal court decisions led the Supreme Court to rule on the restriction of abortion pills.",
          copyright: "Anna Moneymaker/Getty Images",
        },
      ],
      short_url: "https://nyti.ms/41tX9De",
    },
    {
      section: "climate",
      subsection: "",
      title: "Those Seaweed Blobs Headed for Florida? See How Big They Are.",
      abstract:
        "The amount of Sargassum drifting toward North America is a record for the month of March.",
      url: "https://www.nytimes.com/interactive/2023/04/19/climate/seaweed-florida-sargassum.html",
      uri: "nyt://interactive/b7d2e737-d145-5651-a4bb-c7e62017415b",
      byline: "By Elena Shao",
      item_type: "Interactive",
      updated_date: "2023-04-19T09:12:45-04:00",
      created_date: "2023-04-19T05:00:02-04:00",
      published_date: "2023-04-19T05:00:02-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Seaweed",
        "Oceans and Seas",
        "Satellites",
        "Research",
        "Algae",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: ["Florida"],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/18/us/2023-04-17-seaweed-bloom-index/2023-04-17-seaweed-bloom-index-superJumbo-v6.jpg",
          format: "Super Jumbo",
          height: 1333,
          width: 2000,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/18/us/2023-04-17-seaweed-bloom-index/2023-04-17-seaweed-bloom-index-threeByTwoSmallAt2X-v7.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/18/us/2023-04-17-seaweed-bloom-index/2023-04-17-seaweed-bloom-index-thumbLarge-v6.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3KNaPlq",
    },
    {
      section: "us",
      subsection: "politics",
      title:
        "As Fears of Banking Crisis Surged, Members of Congress Sold Bank Shares",
      abstract:
        "The flurry of transactions highlighted how members of Congress continue to buy and sell stocks in industries that intersect with their official duties.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/congress-stock-trading-banks.html",
      uri: "nyt://article/9100702d-5732-5780-bfbb-d1d550426ac1",
      byline: "By Kate Kelly",
      item_type: "Article",
      updated_date: "2023-04-19T19:22:52-04:00",
      created_date: "2023-04-19T17:59:22-04:00",
      published_date: "2023-04-19T17:59:22-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "United States Politics and Government",
        "Banking and Financial Institutions",
        "Conflicts of Interest",
        "Stocks and Bonds",
      ],
      org_facet: [
        "First Republic Bank",
        "House of Representatives",
        "Senate",
        "Silicon Valley Bank",
        "Signature Bank",
        "New York Community Bancorp Inc.",
        "Seacoast Banking Corporation Of Florida",
      ],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-cong-stocks-lqfh/19dc-cong-stocks-lqfh-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1362,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "An account belonging to Representative Jared Moskowitz’s children sold shares of Seacoast Banking Corporation as fears of a banking crisis rattled investors.",
          copyright: "Cliff Owen/Associated Press",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-cong-stocks-lqfh/19dc-cong-stocks-lqfh-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "An account belonging to Representative Jared Moskowitz’s children sold shares of Seacoast Banking Corporation as fears of a banking crisis rattled investors.",
          copyright: "Cliff Owen/Associated Press",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-cong-stocks-lqfh/19dc-cong-stocks-lqfh-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "An account belonging to Representative Jared Moskowitz’s children sold shares of Seacoast Banking Corporation as fears of a banking crisis rattled investors.",
          copyright: "Cliff Owen/Associated Press",
        },
      ],
      short_url: "https://nyti.ms/3MSvtmV",
    },
    {
      section: "us",
      subsection: "politics",
      title:
        "Progressives Organize Fresh Nationwide Push for Changes at the Supreme Court",
      abstract:
        "The drive by more than 30 organizations, some new to the effort, comes as ethics questions have engulfed Justice Clarence Thomas.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/progressives-supreme-court-changes.html",
      uri: "nyt://article/5e54a392-87b4-5a91-b3af-c52c9113de62",
      byline: "By Carl Hulse",
      item_type: "Article",
      updated_date: "2023-04-19T19:48:57-04:00",
      created_date: "2023-04-19T19:00:08-04:00",
      published_date: "2023-04-19T19:00:08-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "United States Politics and Government",
        "Abortion",
        "Polls and Public Opinion",
        "Decisions and Verdicts",
        "Ethics and Official Misconduct",
        "Courts and the Judiciary",
      ],
      org_facet: ["Supreme Court (US)", "Naral Pro-Choice America"],
      per_facet: ["Thomas, Clarence"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-court-gkzh/19dc-court-gkzh-superJumbo.jpg",
          format: "Super Jumbo",
          height: 854,
          width: 1280,
          type: "image",
          subtype: "photo",
          caption:
            "The Senate Judiciary Committee will conduct a hearing exploring the disclosures about Justice Clarence Thomas’s relationship with a billionaire Republican donor.",
          copyright: "Allison V. Smith for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-court-gkzh/19dc-court-gkzh-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "The Senate Judiciary Committee will conduct a hearing exploring the disclosures about Justice Clarence Thomas’s relationship with a billionaire Republican donor.",
          copyright: "Allison V. Smith for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19dc-court-gkzh/19dc-court-gkzh-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "The Senate Judiciary Committee will conduct a hearing exploring the disclosures about Justice Clarence Thomas’s relationship with a billionaire Republican donor.",
          copyright: "Allison V. Smith for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/40lKbGc",
    },
    {
      section: "us",
      subsection: "politics",
      title: "Biden Summons Big Donors to Washington as 2024 Campaign Nears",
      abstract:
        "The gathering is the latest in an intensifying series of planning moves ahead of Mr. Biden’s expected announcement of a re-election bid.",
      url: "https://www.nytimes.com/2023/04/19/us/politics/biden-donors-2024.html",
      uri: "nyt://article/6cf495ec-ce93-57ca-96de-c0ac503c52b1",
      byline:
        "By Maggie Haberman, Shane Goldmacher, Katie Glueck and Rebecca Davis O’Brien",
      item_type: "Article",
      updated_date: "2023-04-19T14:46:25-04:00",
      created_date: "2023-04-19T14:44:43-04:00",
      published_date: "2023-04-19T14:44:43-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Presidential Election of 2024",
        "United States Politics and Government",
        "Campaign Finance",
      ],
      org_facet: ["Democratic National Committee", "Democratic Party"],
      per_facet: ["Biden, Joseph R Jr"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-biden-donors-zbwq/19pol-biden-donors-zbwq-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1365,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "President Biden’s top donors have received invitations to travel to Washington ahead of what is expected to be an expensive 2024 campaign.",
          copyright: "Kenny Holston/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-biden-donors-zbwq/19pol-biden-donors-zbwq-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "President Biden’s top donors have received invitations to travel to Washington ahead of what is expected to be an expensive 2024 campaign.",
          copyright: "Kenny Holston/The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19pol-biden-donors-zbwq/19pol-biden-donors-zbwq-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "President Biden’s top donors have received invitations to travel to Washington ahead of what is expected to be an expensive 2024 campaign.",
          copyright: "Kenny Holston/The New York Times",
        },
      ],
      short_url: "https://nyti.ms/3GWD7c7",
    },
    {
      section: "arts",
      subsection: "music",
      title:
        "Kali Uchis Is a Complicated Musician. She Plans to Stay That Way.",
      abstract:
        "As she begins a headlining tour, the Colombian American songwriter is determined to remain “transparent” and never water down the mix of aesthetics and languages in her genre-crossing music.",
      url: "https://www.nytimes.com/2023/04/19/arts/music/kali-uchis-red-moon-in-venus.html",
      uri: "nyt://article/1a0e3de7-bf46-5ebb-8859-fc126dacabc4",
      byline: "By Jon Pareles",
      item_type: "Article",
      updated_date: "2023-04-19T12:35:24-04:00",
      created_date: "2023-04-19T12:35:24-04:00",
      published_date: "2023-04-19T12:35:24-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: [
        "Content Type: Personal Profile",
        "Latin Music",
        "Red Moon in Venus (Album)",
      ],
      org_facet: [],
      per_facet: ["Kali Uchis (Singer)"],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19KALI-UCHIS-ztlk/19KALI-UCHIS-ztlk-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1536,
          width: 2048,
          type: "image",
          subtype: "photo",
          caption:
            "“I have so many different things that I am,” Kali Uchis said a few days before her Coachella set.",
          copyright: "Elizabeth Weinberg for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19KALI-UCHIS-ztlk/19KALI-UCHIS-ztlk-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption:
            "“I have so many different things that I am,” Kali Uchis said a few days before her Coachella set.",
          copyright: "Elizabeth Weinberg for The New York Times",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/19/multimedia/19KALI-UCHIS-ztlk/19KALI-UCHIS-ztlk-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption:
            "“I have so many different things that I am,” Kali Uchis said a few days before her Coachella set.",
          copyright: "Elizabeth Weinberg for The New York Times",
        },
      ],
      short_url: "https://nyti.ms/43NrYEo",
    },
    {
      section: "crosswords",
      subsection: "",
      title: "Today’s Wordle Review",
      abstract:
        "Our columnist reviews the day’s puzzle. Warning: contains spoilers!",
      url: "https://www.nytimes.com/2023/04/17/crosswords/wordle-review-answer-667.html",
      uri: "nyt://article/7cf81c68-0db4-5f7c-b3ef-970b61cd9722",
      byline: "By Vanessa Friedman",
      item_type: "Article",
      updated_date: "2023-04-17T15:44:33-04:00",
      created_date: "2023-04-17T03:00:04-04:00",
      published_date: "2023-04-17T03:00:04-04:00",
      material_type_facet: "",
      kicker: "",
      des_facet: ["Crossword Puzzles", "Wordle (Puzzle)"],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      multimedia: [
        {
          url: "https://static01.nyt.com/images/2023/04/17/crosswords/17wordle-review-art/17wordle-review-art-superJumbo.jpg",
          format: "Super Jumbo",
          height: 1354,
          width: 2030,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Simone Noronha",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/17/crosswords/17wordle-review-art/17wordle-review-art-threeByTwoSmallAt2X.jpg",
          format: "threeByTwoSmallAt2X",
          height: 400,
          width: 600,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Simone Noronha",
        },
        {
          url: "https://static01.nyt.com/images/2023/04/17/crosswords/17wordle-review-art/17wordle-review-art-thumbLarge.jpg",
          format: "Large Thumbnail",
          height: 150,
          width: 150,
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Simone Noronha",
        },
      ],
      short_url: "https://nyti.ms/3mGOLRm",
    },
  ],
};
